[build]
builder = "NIXPACKS"

# Flask backend
[[services]]
name = "backend"
root = "server"
start = "python run.py"

# React + TS frontend
[[services]]
name = "frontend"
root = "client"
build = "npm install && npm run build"
start = "npx serve -s dist"
